/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 public/models/BookCaseWide.glb -o src/components/BookCase.jsx -r public
Bookcase Wide by Kay Lousberg (https://market.pmnd.rs/model/bookcase-wide)
*/

import { useGLTF } from "@react-three/drei";
import type { JSX } from "react";
import * as THREE from "three";

export default function BookCase(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF("/models/BookCaseWide.glb") as unknown as {
    nodes: {
      Cube033: THREE.Mesh;
      Cube033_1: THREE.Mesh;
      Cube033_2: THREE.Mesh;
      Cube033_3: THREE.Mesh;
      Cube033_4: THREE.Mesh;
      Cube033_5: THREE.Mesh;
      Cube033_6: THREE.Mesh;
      Cube033_7: THREE.Mesh;
      Cube033_8: THREE.Mesh;
    };
    materials: {
      BrownDark_049: THREE.Material;
      PurpleDark_003: THREE.Material;
      White_034: THREE.Material;
      Metal_080: THREE.Material;
      BlueDark_003: THREE.Material;
      GreenDark_007: THREE.Material;
      WoodDark_005: THREE.Material;
      StoneDark_001: THREE.Material;
      Black_030: THREE.Material;
    };
  };
  return (
    <group {...props} dispose={null}>
      <group rotation={[Math.PI / 2, 0, 0]}>
        <mesh
          geometry={nodes.Cube033.geometry}
          material={materials.BrownDark_049}
        />
        <mesh
          geometry={nodes.Cube033_1.geometry}
          material={materials.PurpleDark_003}
        />
        <mesh
          geometry={nodes.Cube033_2.geometry}
          material={materials.White_034}
        />
        <mesh
          geometry={nodes.Cube033_3.geometry}
          material={materials.Metal_080}
        />
        <mesh
          geometry={nodes.Cube033_4.geometry}
          material={materials.BlueDark_003}
        />
        <mesh
          geometry={nodes.Cube033_5.geometry}
          material={materials.GreenDark_007}
        />
        <mesh
          geometry={nodes.Cube033_6.geometry}
          material={materials.WoodDark_005}
        />
        <mesh
          geometry={nodes.Cube033_7.geometry}
          material={materials.StoneDark_001}
        />
        <mesh
          geometry={nodes.Cube033_8.geometry}
          material={materials.Black_030}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/models/BookCaseWide.glb");
