/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 public/models/Couch Small.glb -o src/components/CouchSmall.jsx -r public
Couch Small by Quaternius (https://poly.pizza/m/ZOPP3KzNIk)
*/

import { useGLTF } from "@react-three/drei";
import type { JSX } from "react";
import * as THREE from "three";

export default function CouchSmall(props:JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF("/models/Couch Small.glb") as unknown as {
    nodes: {
      Couch_Small1_1: THREE.Mesh;
      Couch_Small1_2: THREE.Mesh;
    };
    materials: {
      Couch_Blue: THREE.Material;
      Black: THREE.Material;
    };
  };
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <mesh
          geometry={nodes.Couch_Small1_1.geometry}
          material={materials.Couch_Blue}
        />
        <mesh
          geometry={nodes.Couch_Small1_2.geometry}
          material={materials.Black}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/models/Couch Small.glb");
