/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 public/models/Palm tree.glb -o src/components/PalmTree.jsx -r public
Palm tree by jeremy [CC-BY] (https://creativecommons.org/licenses/by/3.0/) via Poly Pizza (https://poly.pizza/m/bjGeBbKhAVN)
*/

import { useGLTF } from "@react-three/drei";
import type { JSX } from "react";
import * as THREE from "three";

export default function PalmTree(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF("/models/Palm tree.glb") as unknown as {
    nodes: {
      "palm_tree_01-Mesh": THREE.Mesh;
      "palm_tree_01-Mesh_1": THREE.Mesh;
      "palm_tree_01-Mesh_2": THREE.Mesh;
    };
    materials: {
      "795548": THREE.Material;
      "8BC34A": THREE.Material;
      DD9944: THREE.Material;
    };
  };
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes["palm_tree_01-Mesh"].geometry}
        material={materials["795548"]}
      />
      <mesh
        geometry={nodes["palm_tree_01-Mesh_1"].geometry}
        material={materials["8BC34A"]}
      />
      <mesh
        geometry={nodes["palm_tree_01-Mesh_2"].geometry}
        material={materials.DD9944}
      />
    </group>
  );
}

useGLTF.preload("/models/Palm tree.glb");
