/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 public/models/Pigeon.gltf -o src/components/Pigeon.jsx -r public
Pigeon by Quaternius (https://poly.pizza/m/9NGlBTpDEr)
*/

import { useGLTF, useAnimations } from "@react-three/drei";
import { useRef, useState, useEffect } from "react";
import * as THREE from "three";
import type { JSX } from "react";
import { SkinnedMesh, Bone } from "three";

export default function Pigeon(props: JSX.IntrinsicElements['group']) {
  const group = useRef<THREE.Group | null>(null);



  const { nodes, materials, animations } = useGLTF("/models/Pigeon.gltf") as unknown as {
    nodes: {
      Root: Bone;
      Cube000: SkinnedMesh;
      Cube000_1: SkinnedMesh;
      Cube000_2: SkinnedMesh;
      Cube000_3: SkinnedMesh;
    };
    materials: {
      Pigeon_Main: THREE.Material;
      Pigeon_Secondary: THREE.Material;
      Eye_White: THREE.Material;
      Eye_Black: THREE.Material;
    };
    animations: THREE.AnimationClip[];
  };


   // 触れた時のアニメーション
   const { actions } = useAnimations(animations, group);
   const [animation, setAnimation] = useState("Flying_Idle");
   
   useEffect(() => {
     if (!actions || !actions[animation]) return;
     
     // アニメーションを開始
     const action = actions[animation];
     action.reset().fadeIn(0.5).play();
     
     // クリーンアップ関数：アニメーションをフェードアウト
     return () => {
       action.fadeOut(0.5);
     };
   }, [animation, actions]);

  return (
    <group {...props} dispose={null} ref={group}       onPointerEnter={() => setAnimation("Yes")}
    onPointerLeave={() => setAnimation("Flying_Idle")}>
      <group name="Scene">
        <group name="CharacterArmature">
          <primitive object={nodes.Root} />
          <group name="Pigeon">
            <skinnedMesh
              name="Cube000"
              geometry={nodes.Cube000.geometry}
              material={materials.Pigeon_Main}
              skeleton={nodes.Cube000.skeleton}
            />
            <skinnedMesh
              name="Cube000_1"
              geometry={nodes.Cube000_1.geometry}
              material={materials.Pigeon_Secondary}
              skeleton={nodes.Cube000_1.skeleton}
            />
            <skinnedMesh
              name="Cube000_2"
              geometry={nodes.Cube000_2.geometry}
              material={materials.Eye_White}
              skeleton={nodes.Cube000_2.skeleton}
            />
            <skinnedMesh
              name="Cube000_3"
              geometry={nodes.Cube000_3.geometry}
              material={materials.Eye_Black}
              skeleton={nodes.Cube000_3.skeleton}
            />
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/models/Pigeon.gltf");